#!/bin/bash
clear
echo "###################################################################"
echo "                            PID ANALYZER" 
echo "                          Installer Program" 
echo "###################################################################"
sudo apt-get update
sudo apt-get install python3-tk
sudo pip3 install numpy
#sudo pip3 install Pillow
sudo pip3 install matplotlib
sudo apt-get install libatlas-base-dev
sudo pip3 install pandas
sudo pip3 install scipy
unzip pid.zip
chmod 755 ./pid/pid
chmod 755 ./pid/*.py
echo "###################################################################"
echo "                        Installation Complete"
echo "                "           
echo " Instructions to run PID ANALYSER" 
echo " 1. cd pid"
echo " 2. ./pid" 
echo "###################################################################"
